// Keep this list in lock-step with backend Permissions.cs. Drift here only affects
// compile-time validation of `<Can permission="...">`; runtime auth always uses the
// backend's claims.
export const PERMISSIONS = [
  'customers.view',
  'customers.create',
  'customers.update',
  'customers.delete',
  'products.view',
  'products.create',
  'products.update',
  'products.delete',
  'quotations.view',
  'quotations.create',
  'quotations.update',
  'quotations.delete',
  'quotations.print',
  'quotations.cancel_confirmed',
  'quotations.view_cost',
  'quotations.view_all',
  'quotations.transfer_own',
  'quotations.transfer_any',
  'quotations.clone_orphan',
  'quotations.bypass_lock',
  'quotations.accounting_confirm',
  'quotations.cancel_accounting_confirmed',
  'users.view',
  'users.create',
  'users.update',
  'users.delete',
  'roles.view',
  'roles.manage',
  'user_settings.manage',
  'system.manage_settings',
  'reports.revenue',
  'reports.profit',
  'reports.debt',
  'reports.delivery',
  'reports.inventory',
  'branches.manage',
  'branches.access_all',
  'period_lock.manage',
  'suppliers.view',
  'suppliers.create',
  'suppliers.update',
  'suppliers.delete',
  'stock_in.view',
  'stock_in.create',
  'stock_in.edit',
  'stock_in.delete',
  'stock_in.cancel',
  'stock_in.edit_all',
  'stock_out.view',
  'stock_out.create',
  'stock_out.edit',
  'stock_out.delete',
  'stock_out.cancel',
  'stock_out.edit_all',
  'inventory.opening_stock',
  'inventory.view_cost',
  'inventory.catalogs.manage',
  'inventory.settings',
  'inventory.recalc_cost',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLES = ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTANT', 'MANAGER'] as const;
export type Role = (typeof ROLES)[number];
